create table Zlecenia
(
    Indeks               int not null
        primary key,
    Archiwum             int,
    Data                 datetime,
    DataWejscia          datetime,
    DataZakonczenia      datetime,
    Del                  int,
    Diler                varchar(250),
    FirstStanowisko      int,
    Hiden                int,
    ErrIdx               int,
    Klient               varchar(250),
    LiczbaSzklen         int,
    NipDilera            varchar(250),
    Oscieznica           int,
    Pozycja              int,
    Skanowanie           int,
    Skrzydlo             int,
    srcdoc               int,
    Stanowisko           int,
    StanowiskoPoprzednie int,
    Sztuka               int,
    TerminRealizacji     varchar(250),
    Zakonczone           int,
    Zlecenie             varchar(250),
    ZlecenieDilera       varchar(50),
    DodOpis              varchar(250),
    optym                int,
    TerminProdukcji      varchar(250),
    Optymalizacja        varchar(250),
    DbWHOkna             int,
    KodBiura             varchar(250),
    OptSrcdoc            int,
    Vip                  int,
    ObrazekOsc           varchar(250),
    ObrazekSkr           varchar(250),
    Referencja           varchar(250),
    Priorytet            int,
    IloscJedn            float,
    Idx_typu             int,
    Typ                  varchar(250),
    IloscJednPoz         float,
    PozycjaLp            int,
    Country              varchar(250),
    FrameWidth           int,
    FrameHeight          int,
    SashWidth            int,
    SashHeight           int,
    Glazing              varchar(250),
    GlazingFrame         varchar(250),
    GlazingFrameColor    varchar(250),
    Color                varchar(250),
    Paczka               varchar(250)
)
go

